version: '3.5'
services:
  product-app:
    depends_on:
      product-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    container_name: product-app
    build:
      context: .
      dockerfile: Dockerfile
    image: product-app:latest
    ports:
      - '19999:19999'
      - '5005:5005'
    networks:
      - app
      - db
    healthcheck:
      test: "wget -qO- http://localhost:8080/actuator/health/ | grep UP || exit 1"
      timeout: 30s
      retries: 10
  product-db:
    container_name: product-db
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: 'product_db'
      MYSQL_USER: 'productAdmin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./product-db:/var/lib/mysql
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - db
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 30s
      retries: 10
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.9-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - app
    environment:
      - "RABBITMQ_DEFAULT_PASS=pass"
      - "RABBITMQ_DEFAULT_USER=user"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
volumes:
  product-db:
  docker-entrypoint-initdb.d:
networks:
  app:
    external: true
    driver: bridge
  db:
    external: true
    driver: bridge